repos:
  # 🔑 Gitleaks - secret scanning (all file types)
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args:
          [
            "detect",
            "--redact",             # hide secret values in output
          ]

  # 📦 Config file validity + large file prevention
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=512"]

  # 🧹 Formatting / safety extras
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.4.0
    hooks:
      - id: eslint
        additional_dependencies: ["eslint@9.4.0"]
