[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = "AKIA[0-9A-Z]{16}"
tags = ["AWS"]

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
tags = ["AWS"]
