name: Gitleaks Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全歷史掃描的關鍵

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-results.sarif --exit-code=1

      - name: Upload Gitleaks Results
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-results.sarif

permissions:
  contents: read
