name: Gitleaks Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必須獲取完整歷史記錄以進行全面掃描

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # 如果您有 Gitleaks Pro 授權