- name: Install Gitleaks
  run: |
    wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz -O gitleaks.tar.gz
    tar -xf gitleaks.tar.gz gitleaks
    sudo mv gitleaks /usr/local/bin/gitleaks

- name: Run Gitleaks Full History Scan
  run: |
    gitleaks detect --source . \
      --report-format sarif \
      --report-path gitleaks-results.sarif \
      --exit-code=1

- name: Upload Gitleaks Results
  uses: actions/upload-artifact@v4
  with:
    name: gitleaks-report
    path: gitleaks-results.sarif
