name: Gitleaks Scan

on:
  push:
    branches: ['**']
  
  pull_request:
    branches: ['**']

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: read # 僅允許讀取儲存庫內容

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 獲取完整歷史記錄以進行全面掃描

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_SCAN_HISTORY: true # 啟用全歷史掃描
